name: Tests CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build --if-present
#      - run: npm test

# Pasted in node-deploy.yml between "steps" and "deploy to server"
#      - uses: actions/checkout@v2
#        with:
#          ref: dev
#      - uses: actions/setup-node@v1
#      - run: npm install
#
#      - run: |
#          touch .env
#          echo DB_HOST = "$DB_HOST" >> .env
#          echo DB_PW = "$DB_PW" >> .env
#          echo DB_USER = "$DB_USER" >> .env
#          echo DB_NAME = "$DB_NAME" >> .env
#          echo CLIENT_ID = "$CLIENT_ID" >> .env
#          echo CLIENT_SECRET = "$CLIENT_SECRET" >> .env
#
#      - run: npm run bundle